spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123.123.
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: false
server:
  port: 8081
  servlet:
    context-path: /demo
